### ISSUE TITLE
Connection With Proxy

### ISSUE THREAD

**Issue by jbdeandrade** [gpotter2/SSLKeystoreFactories#1]
With this code it is possible to connect through a proxy server?

Thanks for listening

**Comment by gpotter2** [comment]
Well that's an interresting question..... I never tried ... If it's possible, please tell me about it :)

Sorry :)

**Comment by gpotter2** [comment]
Well !

I've done some edits, you should be able to do it with the following code... Haven't tested .... Plz tell me if it works.

**Comment by gpotter2** [comment]
The new version (btw with many bugs corrected) should works with it.
